# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_visit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('normalizedLevel', models.FloatField()),
                ('textDesc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BiasSetDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('nrLevels', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('bias', models.ManyToManyField(to='api.BiasDefinition')),
            ],
        ),
        migrations.AddField(
            model_name='biasdefinition',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biases', to='api.BiasSetDefinition'),
        ),
    ]
