# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170710_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasdefinition',
            name='levelLabel',
            field=models.CharField(default=-9, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biasdefinition',
            name='level',
            field=models.IntegerField(),
        ),
    ]
