# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170712_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasdefinition',
            name='tag',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
