# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_biasdefinition_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
